print("Welcome to the delegation link generator: Easy-Delegate.")
delegator = input("\n Who is the delegator? \n")
delegatee = input("\n Who is the delegatee? \n")
vesting_shares = input("\n Amount of the delegation: \n")

print("\n Generating ...")
print("\n Link:")
print("https://hivesigner.com/sign/delegateVestingShares?delegator={}&delegatee={}&vesting_shares={}%20HP".format(delegator, delegatee, vesting_shares))
print("\n Recap: \n \n Delegator : {} \n Delegatee : {} \n Vesting_shares : {}".format(delegator, delegatee, vesting_shares))
print("Copy the generated link and paste it into the navigation bar of your internet browser.")
finish = input(" \n Press on 'ENTER' when it's done :)")
